name: CI

on:
  push:
    branches:
      - main
      - windows
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Server 2019 [Debug]",
            os: windows-2019,
            extra: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake",
            exclude: "-E mqtt"
          }
          - {
            name: "macOS 11.0 AppleClang 12 [Release]",
            os: macos-11.0,
            extra: "-G Ninja",
            cxx: "-DCMAKE_CXX_COMPILER=clang++"
          }
          - {
            name: "macOS 11.0 GCC 10 [Release]",
            os: macos-11.0,
            extra: "-G Ninja",
            cxx: "-DCMAKE_CXX_COMPILER=g++-10"
          }
          - {
            name: "Ubuntu 20.04 Clang 11 [Release]",
            os: ubuntu-20.04,
            extra: "-G Ninja",
            cxx: "-DCMAKE_CXX_COMPILER=clang++-11"
          }
          - {
            name: "Ubuntu 20.04 GCC 10 [Release]",
            os: ubuntu-20.04,
            extra: "-G Ninja",
            cxx: "-DCMAKE_CXX_COMPILER=g++-10"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Get macOS Concurrency
      if: runner.os == 'macOS'
      run: |
        echo NPROC="sysctl -n hw.ncpu" >> $GITHUB_ENV
        echo "Running on $(sysctl -n hw.ncpu) threads ..."

    - name: Get Linux Concurrency
      if: runner.os == 'Linux'
      run: |
        echo NPROC="nproc" >> $GITHUB_ENV
        echo "Running on $(nproc) threads ..."

    - name: Set Up Windows Dependencies
      if: runner.os == 'Windows'
      run: |
        vcpkg install mosquitto:x64-windows rapidjson:x64-windows
        vcpkg integrate install

    - name: Set Up macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install ninja gcc@10 rapidjson mosquitto
        export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
        brew services start mosquitto

    - name: Set Up Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt install -y cmake ninja-build pkg-config clang-11 g++-10 mosquitto libmosquittopp-dev rapidjson-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}${{matrix.confix.windowspath}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{runner.workspace}}/opera -DCMAKE_BUILD_TYPE=$BUILD_TYPE ${{matrix.config.cxx}} ${{matrix.config.extra}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC)

    - name: Build Tests
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC) --target tests

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -j $($NPROC) --output-on-failure