name: CI

on:
  push:
    branches:
      - main
      - kafka
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "macOS 11.0 GCC 10 [Release]",
            os: macos-11.0,
            cxx: "g++-10"
          }
          - {
            name: "Ubuntu 20.04 Clang 11 [Release]",
            os: ubuntu-20.04,
            cxx: "clang++-11"
          }
          - {
            name: "Ubuntu 20.04 GCC 10 [Release]",
            os: ubuntu-20.04,
            cxx: "g++-10"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Get macOS Concurrency
      if: runner.os == 'macOS'
      run: |
        echo NPROC="sysctl -n hw.ncpu" >> $GITHUB_ENV
        echo "Running on $(sysctl -n hw.ncpu) threads ..."

    - name: Get Linux Concurrency
      if: runner.os == 'Linux'
      run: |
        echo NPROC="nproc" >> $GITHUB_ENV
        echo "Running on $(nproc) threads ..."

    - name: Set Up macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install ariadne-cps/tap/ariadne
        brew install ninja gcc@10 rapidjson kafka
        HOMEBREW_CXX=g++-10 HOMEBREW_CC=gcc-10 brew install librdkafka --build-from-source
        export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig

    - name: Set Up Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository ppa:ariadne-cps/ariadne
        sudo apt install -y cmake ninja-build pkg-config clang-11 g++-10 librdkafka-dev rapidjson-dev ariadne
        export KAFKA_PARENT_DIR=~
        cd $KAFKA_PARENT_DIR
        wget https://archive.apache.org/dist/kafka/2.8.0/kafka-2.8.0-src.tgz
        tar -xvf kafka-2.8.0-src.tgz
        cd kafka-2.8.0-src
        ./gradlew jar -PscalaVersion=2.13.5
        cd bin
        ln -s zookeeper-server-start.sh zookeeper-server-start
        ln -s kafka-server-start.sh kafka-server-start
        ln -s zookeeper-server-stop.sh zookeeper-server-stop
        ln -s kafka-server-stop.sh kafka-server-stop
        ln -s kafka-topics.sh kafka-topics
        echo "export PATH=\"\$PATH:$KAFKA_PARENT_DIR/kafka-2.8.0-src/bin\"" >> ~/.bashrc
        source ~/.bashrc

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=${{matrix.config.cxx}} -G "Ninja" -DWERROR=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC)

    - name: Build Tests
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC) --target tests

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -j 1 --output-on-failure --verbose